name: Resume Ranking Workflow

on:
  workflow_dispatch:
  push:
   branches:
    - UnitTesting 

  pull_request:
    types: [opened]
    branches:
      - main
      
jobs:
  build:
    name: Build & Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Next.js build cache
        uses: actions/cache@v3
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

      - name: Install dependencies
        run: npm ci

    
